### PR TITLE
brielle_updated_css_andjs_files

### PR DESCRIPTION
**Pull request by BMccorm**
added css and updates to js functions

### CODE REVIEW

**Review by herivillaz — APPROVED** [review]
lgfm

**Review by khantatyana — APPROVED** [review]

**Comment by BMccorm** [comment]
test

**Review by edithdaria — APPROVED** [review]
looks good

**Review by margaretseiche — APPROVED** [review]
Looks good

**Comment by margaretseiche** [comment]
Closing to allow for pushing without result.js

**Pull request closed without merging**
